
all:
	cd gaia; make all
	cd src; make all


# At present there's no method to delete the contents of the database
#   from w/in the program, so add a way to do so outside.
refresh_db:
	cd gaia/ && make gaiac


refresh:
	cd gaia; make refresh
	cd src; make refresh

clean:
	cd gaia; make clean
	cd src; make clean

